name: GitHub Actions
run-name: Testing Github Actions
on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
  push:
    branches: [ main ]
    
jobs:
  java-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "Temurin"

      - name: Run Tests
        run: mvn test
